version: "3.9"
services:
  db:
    image: mysql
    restart: on-failure
    container_name: db
    hostname: db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: jonas
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: calculator
  calculator:
    restart: on-failure
    build: .
    container_name: calculator
    ports:
      - "3000:3000"
    depends_on:
      - db
    external_links:
      - db
    environment:
      - ROUTE_API=/api/v1/
      - MYSQL_USER=jonas
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=calculator
      - MYSQL_HOST=db
    volumes:
      - .:/home/app